import path from 'node:path';
import type { OutputFormat } from '../render/render.types.js';
import type { DrawnFile } from './draw.types.js';

/** Where `--all` lands by default, so ten files do not land in the repository root. */
export const ALL_DIR = 'diagrams';

const EXTENSION: Record<OutputFormat, string> = {
  svg: '.svg',
  png: '.png',
  dot: '.dot',
  mmd: '.mmd',
  json: '.graph.json',
};

export const extensionOf = (format: OutputFormat): string => EXTENSION[format];

/** `--out` names a file when it ends in the format's extension; anything else is a folder. */
export const namesFile = (out: string, format: OutputFormat): boolean =>
  out.toLowerCase().endsWith(EXTENSION[format]) ||
  (format === 'json' && out.toLowerCase().endsWith('.json'));

/**
 * One pipeline: `./<id>.svg` in the repository root by default, `<dir>/<id>.svg` for a folder,
 * exactly the file for a file. Every path is made absolute against the root.
 */
export const outputFileFor = (
  rootPath: string,
  id: string,
  format: OutputFormat,
  out: string | undefined,
): string => {
  const name: string = `${id}${EXTENSION[format]}`;
  if (out === undefined) return path.join(rootPath, name);
  const absolute: string = path.resolve(rootPath, out);
  return namesFile(out, format) ? absolute : path.join(absolute, name);
};

/** `--all`: a folder, `./diagrams` by default; a file name is refused by the caller. */
export const outputDirForAll = (rootPath: string, out: string | undefined): string =>
  path.resolve(rootPath, out ?? ALL_DIR);

/** The `index.md` listing an `--all` run writes beside the diagrams. */
export const indexMarkdown = (files: readonly DrawnFile[], directory: string): string =>
  [
    '# Factory diagrams',
    '',
    'Generated by `factory-diagram --all`; re-run it after editing a `pipeline.json`.',
    '',
    ...files.map((file: DrawnFile): string => {
      const relative: string = path.relative(directory, file.file).split(path.sep).join('/');
      return `- [${file.id}](./${relative})`;
    }),
    '',
    ...files.map((file: DrawnFile): string => {
      const relative: string = path.relative(directory, file.file).split(path.sep).join('/');
      return `## ${file.id}\n\n![${file.id}](./${relative})\n`;
    }),
  ].join('\n');
