import { describe, expect, it } from 'vitest';
import type { GraphModel } from '../src/features/graph/index.js';
import { renderNative } from '../src/features/render/native/index.js';
import { pillsFor, roundedPath, wrapSlug } from '../src/features/render/native/native.utils.js';
import { renderOptionsSchema } from '../src/features/render/render.schema.js';
import type { RenderOptions, RenderResult } from '../src/features/render/render.types.js';
import { fixtureFile, modelOf, portable } from './helpers.js';

const options = (overrides: Partial<RenderOptions> = {}): RenderOptions =>
  renderOptionsSchema.parse({ version: 'test', ...overrides });

const render = (reference: string, overrides: Partial<RenderOptions> = {}): RenderResult =>
  renderNative(portable(modelOf(reference)), options(overrides));

const count = (text: string, pattern: RegExp): number => (text.match(pattern) ?? []).length;

describe('the native SVG', () => {
  it.each([
    'linear',
    'fan-out-fan-in',
    'review-loop',
    'shortcut-jump',
    'human-gate',
    'dangling-unreachable',
  ])('fixture %s matches its snapshot', (name: string) => {
    expect(render(fixtureFile(name)).svg).toMatchSnapshot();
  });

  it('is byte-identical across runs', () => {
    expect(render('quick-research-factory').svg).toBe(render('quick-research-factory').svg);
  });

  it('is self-contained: no CSS variables, a style block, a version comment without a date', () => {
    const { svg } = render('quick-research-factory');
    expect(svg).not.toContain('var(--');
    expect(svg).toContain('<style>');
    expect(svg).toContain(
      '<!-- generated by draw-factory test from factories/quick-research-factory/pipeline.json -->',
    );
    expect(svg).not.toMatch(/\d{4}-\d{2}-\d{2}/);
  });

  it('quick-research-factory: the review → write-report loop shows ×3 and the escape to finalize is labelled max', () => {
    const { svg } = render('quick-research-factory');
    expect(svg).toContain('↺ REVISE ×3');
    expect(svg).toContain('data-edge="e:review-&gt;finalize:max"');
    expect(svg).toMatch(/data-edge-label="e:review-&gt;finalize:max"[^]*?>max</);
    expect(count(svg, /class="card[ "]/g)).toBe(6);
  });

  it('draws a human gate dashed with a glyph, an unreachable step with a badge', () => {
    expect(render(fixtureFile('human-gate')).svg).toMatch(/class="card is-human"[^]*?gate-glyph/);
    expect(render(fixtureFile('dangling-unreachable')).svg).toMatch(
      /class="card is-unreachable"[^]*?warn-badge/,
    );
  });

  it('lays pills above every line so a fan-out trunk never crosses a word', () => {
    const { svg } = render(fixtureFile('fan-out-fan-in'));
    const graph: string = svg.slice(
      svg.indexOf('<g class="graph"'),
      svg.indexOf('<g class="legend"'),
    );
    const lastPath: number = graph.lastIndexOf('<path class="edge-path"');
    const firstPill: number = graph.indexOf('<g class="pills">');
    expect(firstPill).toBeGreaterThan(lastPath);
  });

  it('honours --hide legend,title,loops,max and --highlight', () => {
    const { svg, warnings } = render('quick-research-factory', {
      hide: ['legend', 'title', 'loops', 'max'],
      highlight: ['review', 'nope'],
    });
    expect(svg).not.toContain('class="legend"');
    expect(svg).not.toContain('class="title"');
    expect(svg).not.toContain('class="edge edge-loop');
    expect(svg).not.toContain(':max"');
    expect(svg).toContain('class="card is-highlight" data-step="review"');
    expect(warnings).toEqual(['--highlight nope: no such step']);
  });

  it('refuses what v1 does not draw yet, naming what it does', () => {
    expect(() => render(fixtureFile('linear'), { theme: 'dark' })).toThrow(
      /--theme dark is not implemented/,
    );
    expect(() => render(fixtureFile('linear'), { view: 'detailed' })).toThrow(/--view detailed/);
    expect(() => render(fixtureFile('linear'), { direction: 'TB' })).toThrow(/--direction TB/);
  });

  it('keeps every card and lane inside the canvas', () => {
    const model: GraphModel = portable(modelOf('strategy-research-factory'));
    const { svg } = renderNative(model, options());
    const [, w, h] = /width="(\d+)" height="(\d+)"/.exec(svg) ?? [];
    const [, tx, ty] = /class="graph" transform="translate\(([-\d.]+) ([-\d.]+)\)"/.exec(svg) ?? [];
    const rects: RegExpMatchArray[] = [
      ...svg.matchAll(/<rect class="card-box" x="([-\d.]+)" y="([-\d.]+)"/g),
    ];
    expect(rects.length).toBe(model.stepCount);
    for (const r of rects) {
      expect(Number(r[1]) + Number(tx)).toBeGreaterThanOrEqual(0);
      expect(Number(r[2]) + Number(ty)).toBeGreaterThanOrEqual(0);
      expect(Number(r[1]) + Number(tx) + 156).toBeLessThanOrEqual(Number(w));
      expect(Number(r[2]) + Number(ty) + 104).toBeLessThanOrEqual(Number(h));
    }
  });
});

describe('native helpers', () => {
  const width = (t: string): number => t.length * 8;

  it('wraps a slug after hyphens onto at most two lines and ellipsizes the rest', () => {
    expect(wrapSlug('frame-question', 132, 2, width)).toEqual(['frame-question']);
    expect(wrapSlug('improve-pipeline-forever', 132, 2, width)).toEqual([
      'improve-',
      'pipeline-forever',
    ]);
    expect(wrapSlug('review-operational-excellence', 132, 2, width)).toEqual([
      'review-',
      'operational-exc…',
    ]);
  });

  it('badges only loops with ×N and lights only the happy result', () => {
    expect(pillsFor(['REVISE'], 'loop', 3, false, true).map((p) => p.text)).toEqual([
      '↺ REVISE ×3',
    ]);
    expect(pillsFor(['REVISE'], 'loop', 3, false, false).map((p) => p.text)).toEqual(['↺ REVISE']);
    expect(
      pillsFor(['DONE', 'FAIL'], 'forward', 2, true, true).map((p) => [p.text, p.lit]),
    ).toEqual([
      ['DONE', true],
      ['FAIL', false],
    ]);
  });

  it('rounds corners and drops zero-length segments', () => {
    expect(
      roundedPath([
        { x: 0, y: 0 },
        { x: 10, y: 0 },
      ]),
    ).toBe('M 0 0 L 10 0');
    expect(
      roundedPath([
        { x: 0, y: 0 },
        { x: 0, y: 0 },
        { x: 20, y: 0 },
        { x: 20, y: 20 },
      ]),
    ).toBe('M 0 0 L 14 0 Q 20 0 20 6 L 20 20');
  });
});
